# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57cbc662b45f529bf843a73182f9669d318be2cfd66683460774db2202e299e0579cf9257027efb69bc89a466113d977e6cbb187376b8ec9ef2d1aca0c576ba6

test:
  secret_key_base: a5c42fb0cd75798775ae0c1f5a05ead572af546353e86bbb3cc535f498600e86b75011298ebc02c5ccf281144870450ccfa0bfcb5d47423ecebe70d48044d3ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
